# Generated by Django 2.1.7 on 2019-03-15 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerator', '0002_auto_20190315_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
