# Generated by Django 2.1.7 on 2019-03-15 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionGenerator', '0003_auto_20190315_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Typesofuser',
        ),
    ]
