# Generated by Django 2.1.7 on 2019-03-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerator', '0005_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='year',
            field=models.IntegerField(),
        ),
    ]
