# Generated by Django 2.1.7 on 2019-04-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerator', '0010_subcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='chapter',
            field=models.CharField(default=None, max_length=299),
        ),
    ]
